name: Matrix
on: push

jobs:
  runs-on: ubuntu-latest
  node-version:
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Log node version
        run: node -v
