name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [10, 12, 14]
      # fail-fast: true
      # max-parallel: 2
    runs-on: ${{ matrix.os }}  # mac -> ubuntu -> windows
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}   # 10 -> 12 -> 14
      - name: Log node version
        run: node -v
